table discount
	lineageTag: 86a667fe-4327-44f5-b8d7-eb18366cd8d9

	column OrderNumber
		dataType: int64
		formatString: 0
		lineageTag: ee2ac743-487f-41a8-801b-9205d3de469b
		summarizeBy: none
		sourceColumn: OrderNumber

		annotation SummarizationSetBy = Automatic

	column discountValue
		dataType: double
		lineageTag: 0527c50d-7989-4d22-85b9-03de002c814b
		summarizeBy: sum
		sourceColumn: discountValue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DiscountSequence
		dataType: int64
		formatString: 0
		lineageTag: b84d81cd-6268-4445-b0bc-f499c190c203
		summarizeBy: sum
		sourceColumn: DiscountSequence

		annotation SummarizationSetBy = Automatic

	partition discount = m
		mode: import
		source =
				let
				    Source = Json.Document(File.Contents("C:\Users\KlausFolz\Desktop\Repositories\DataMechanics\Posts\Chain discount\Data\discount.json")),
				    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"OrderNumber", "discountValue", "DiscountSequence"}, {"OrderNumber", "discountValue", "DiscountSequence"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Column1",{{"OrderNumber", Int64.Type}, {"discountValue", type number}, {"DiscountSequence", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

